=== _Задание_:

- Светодиоды должны моргать раз в 500 мс.
- Сделать задержку на 500, 1000, 1500 мс, вместо цикла _**for(..)**_ с помощью таймера.

=== _Код программы_

----
#include "rccregisters.hpp"
#include "gpiocregisters.hpp"
#include "gpioaregisters.hpp"
#include "tim2registers.hpp"
#include <iostream>

constexpr std::uint32_t CpuClock = 8'000'000U;
auto delay_ms(std::uint32_t ButPeriod)
{
  TIM2::CR1::URS::OverflowEvent::Set();
  const std::uint32_t timerValue = (CpuClock * 1000U) * ButPeriod - 1U;
  TIM2::ARR::Write(timerValue);
  TIM2::SR::UIF::NoInterruptPending::Set();
  TIM2::CNT::Write(0);
  TIM2::CR1::CEN::Enable::Set();

  while(!TIM2::SR::UIF::NoInterruptPending::IsSet())
  {
  }
  TIM2::CR1::CEN::Disable::Set();
}

int main()
{
  unsigned int ButPeriod = 100U;
  unsigned int LedsPeriod = 500U;
  unsigned int counter = 0;

  bool flag = false;
  RCC::CR::HSEON::On::Set();
  while(!RCC::CR::HSERDY::Ready::IsSet())
  {
  }
  RCC::CFGR::SW::Hse::Set();
  while(!RCC::CFGR::SWS::Hse::IsSet())
  {
  }
  RCC::AHB1ENR::GPIOCEN::Enable::Set();
  RCC::AHB1ENR::GPIOAEN::Enable::Set();
  GPIOC::MODER::MODER5::Output::Set();
  GPIOC::MODER::MODER13::Input::Set();
  GPIOA::MODER::MODER5::Output::Set();
  GPIOC::MODER::MODER9::Output::Set();
  GPIOC::MODER::MODER8::Output::Set();
  RCC::APB1ENR::TIM2EN::Enable::Set();
  for(;;)
  {
    delay_ms(ButPeriod);
    if(GPIOC::IDR::IDR13::Low::IsSet())
    {
      LedsPeriod += 100U;
      counter = 0;
    }
    counter = counter + ButPeriod;
    if(counter >= LedsPeriod)
    {
      if(!flag)
      {
        GPIOC::BSRR::BS8::High::Write();
        GPIOC::BSRR::BS9::High::Write();
        GPIOC::BSRR::BS5::High::Write();
        GPIOA::BSRR::BS5::High::Write();
        flag = true;
      }
    else
    {
      GPIOC::BSRR::BR9::Low::Write();
      GPIOC::BSRR::BR8::Low::Write();
      GPIOC::BSRR::BR5::Low::Write();
      GPIOA::BSRR::BR5::Low::Write();
      flag = false;
    }
    counter = 0;
    }
  }
  return 1;
}

----

=== _Описание действий_

Работаем от внешнего источника частоты _HSE_ (8 МГц). Для начала необходимо подать
тактирование на модуль таймера. Нужно подключить таймер к системе тактирования
(шине _APB1_), для того чтобы таймер заработал.

 RCC::APB1ENR::TIM2EN::Enable::Set();

Для организации задержки необходимо для начала установить источник генерации
прерываний по событию переполнений с помощью бита _URS_ в регистре _CR1_:

 TIM2::CR1::URS::OverflowEvent::Set();

Далее необходимо установить такое значение, до которого счётчик будет считать
в регистре перезагрузки _ARR_:

 const std::uint32_t timerValue = (CpuClock * 1000U) * ButPeriod - 1U;
 TIM2::ARR::Write(timerValue);

Затем нужно скинуть флаг генерации прерывания _UIF_ по событию в регистре _SR_:

 TIM2::SR::UIF::NoInterruptPending::Set();

После этого установим начальное значение счётчика в значение 0 в регистре _CNT_:

 TIM2::CNT::Write(0);

Запустим счетчик с помощью бита _EN_ в регистре _CR1_:

 TIM2::CR1::CEN::Enable::Set();


Затем надо проверять пока не будет установлен флаг генерации прерывания по
событию _UIF_ в регистре _SR_:

    while (!TIM2::SR::UIF::NoInterruptPending::IsSet())
    {
    }

Как только флаг установлен остановить счетчик, сбросить бит _EN_ в регистре _CR1_.
Сбросить флаг генерации прерывания _UIF_ по событию в регистре _SR_.

 TIM2::CR1::CEN::Disable::Set();

